### ISSUE TITLE
go-test-current-test doesn't run Example function that is placed after Test function

### ISSUE THREAD

**Issue by kostya-sh** [nlamirault/gotest.el#18]
The following code can be used to reproduce:

    package main

    import (
    	"fmt"
    	"testing"
    )

    func TestA(t *testing.T) {
    	t.Logf("test")
    }

    func ExampleB() {
    	fmt.Println("Example")
    	// Output:
    	// Example
    }

Running `go-test-current-file` with the cursor inside `ExampleB` results in `unable to find test` error.

**Comment by nlamirault** [comment]
With last version, i've got this output : 

```go
package main

import (
	"fmt"
	"testing"
)

func TestA(t *testing.T) {
	fmt.Println("test a")
}

func TestAB(t *testing.T) {
	fmt.Println("test ab")
}

func ExampleB() {
	fmt.Println("Example")
}

func BenchmarkHello(b *testing.B) {
	for i := 0; i < b.N; i++ {
		fmt.Sprintf("hello")
	}
}
```

```bash
$ go test -run='TestA|TestAB|ExampleB'
test a
test ab
PASS
ok  	_/home/nlamirault/gotest.el/var	0.002s
```

**Comment by kostya-sh** [comment]
Sorry, I meant `go-test-current-test` function, not `go-test-current-file`. The title of the issue is correct, but the body mentioned wrong function.

**Comment by kostya-sh** [comment]
Also I am not sure if `go-test-current-file` should run benchmarks. A separate function would be more usable as benchmarks usually long running.
