### ISSUE TITLE
go-test-current-file runs all tests in the current package

### ISSUE THREAD

**Issue by kostya-sh** [nlamirault/gotest.el#30]
This is due to slightly wrong regex:

    go test -run='TestA|TestB|'

while it should be 

    go test -run='TestA|TestB'

**Comment by nlamirault** [comment]
There is a unit test which use file **test/go_test.go**, and regex seems to be   "TestFoo|TestBar|Test_Baz" not  "TestFoo|TestBar|Test_Baz|".

```elisp
(ert-deftest test-go-test-get-current-file-tests ()
  :tags '(find)
  (with-test-sandbox
   (with-current-buffer (find-file-noselect testsuite-buffer-name)
     (should (string= "TestFoo|TestBar|Test_Baz"
                      (go-test--get-current-file-tests))))))
```

And on this file, if we make *M-x go-test-current-file*, the command is : 

```bash
$ go test -run='TestFoo|TestBar|Test_Baz'
```

**Comment by kostya-sh** [comment]
`go-test--get-current-file-tests` works. However `go-test-current-file` combines `go-test--get-current-file-tests` with `go-test--get-current-file-examples`. If there are no examples in the test file an extra `|` is added.

**Comment by DavidHuie** [comment]
I can confirm that the extra `|` is being added to end of the `-run` argument.
