### ISSUE TITLE
go-test-* Always opens a new buffer 

### ISSUE THREAD

**Issue by licorna** [nlamirault/gotest.el#40]
When running any of the go-test-* (like go-test-current-file or go-test-current-project) the *Go Test* buffer appears in a new window all the time, quickly filling my Emacs frame, also, the old window with the *Go Test* buffer moves to some other buffer and it gets messy very rapidly.

Is it possible to have the *Go Test* buffer always appear in the same window and not spliting my frame at all after a *Go Test* buffer is already visible?

**Comment by nlamirault** [comment]
@antifuchs make a PR which seems solve this request. 
@licorna could you confirm ?

**Comment by licorna** [comment]
I can confirm it is working on my setup with Emacs 25.1.1

Thanks!
